src/main/java/sk/tuke/juho/beans/LanguageBean.java
package sk.tuke.juho.beans;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;


/**
 * Created by Juraj Horbaľ on 2/28/2017. Poskytuje podporu pre jazyky
 */

@ManagedBean(name="language")
@SessionScoped
public class LanguageBean implements Serializable{

    private static final long serialVersionUID = 1L;

    private String localeCode;

    private static Map<String,Object> countries;
    static{
        countries = new LinkedHashMap<String,Object>();
        countries.put("English", Locale.ENGLISH); //label, value
        countries.put("Slovenský",new Locale("sk_SK","SVK"));
    }

    /**
     *
     * @return map of localizations
     */
    public Map<String, Object> getCountriesInMap() {
        return countries;
    }

    /**
     *
     * @return current locale code
     */
    public String getLocaleCode() {
        if(localeCode==null)
            localeCode="Slovenský";
        return localeCode;
    }

    /**
     *
     * @param localeCode current locale code
     */
    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }

    /**
     * value change event listener
     * @param e event
     */
    public void countryLocaleCodeChanged(ValueChangeEvent e){

        String newLocaleValue = e.getNewValue().toString();

        //loop country map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

            if(entry.getValue().toString().equals(newLocaleValue)){

                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale)entry.getValue());

            }
        }
    }

}

src/main/webapp/templates/content.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<body>
<ui:composition>
    <div class="container">
        <h1>#{msg['lang.page_name']}</h1>
        <h3>#{msg['thesis']}</h3>
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action active">
                <h5 class="list-group-item-heading">#{msg['supervisor']}</h5>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <p class="list-group-item-text">Ing. Csaba Szabó, PhD.</p>
            </a>
        </div>
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action active">
                <h5 class="list-group-item-heading">#{msg['instructions']}</h5>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <p class="list-group-item-text">1. Naštudovať problematiku testovania softvéru.</p>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <p class="list-group-item-text">2. Naštudovať problematiku cloud-u.</p>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <p class="list-group-item-text">3. Navrhnúť testvér pre regresné testovanie ako službu cloud-u.</p>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <p class="list-group-item-text">4. Implementovať navrhnutú službu</p>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <p class="list-group-item-text">5. Vypracovať dokumentáciu podľa pokynov vedúceho práce</p>
            </a>
        </div>
    </div>
</ui:composition>
</body>
</html>

src/main/webapp/templates/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
>
<body>
<ui:composition>
    <div class="footer" align="center">
        <div>
            <p>#{msg['lang.created']} bc. Juraj Horbaľ<br/>
                © Copyright 2017. #{msg['lang.copyright']}</p>
        </div>
    </div>
    <h:outputScript library="webjars" name="jquery/2.1.4/jquery.min.js"/>
    <h:outputScript library="webjars" name="bootstrap/3.3.6/js/bootstrap.min.js"/>
    <h:outputScript library="js" name="/lib/jquery.dataTables.min.js"/>
    <h:outputScript library="js" name="/lib/dataTables.bootstrap.min.js"/>
    <h:outputScript library="js" name="/lib/dataTables.responsive.min.js"/>
    <h:outputScript library="js" name="/lib/responsive.bootstrap.min.js"/>
    <h:outputScript library="js" name="/core.js"/>
</ui:composition>
</body>
</html>

src/main/webapp/templates/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:c="http://java.sun.com/jsp/jstl/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
>
<ui:composition>
    <h:outputStylesheet library="css" name="bootstrap.min.css"/>
    <h:outputStylesheet library="webjars" name="font-awesome/4.5.0/css/font-awesome.min-jsf.css"/>
    <h:outputStylesheet library="css" name="core.css"/>
    <f:view locale="#{language.localeCode}"/>
    <div class="header">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">#{msg['lang.page_name']}</a>
                </div>
                <ul class="nav navbar-nav">
                    <c:if test="#{!adminBean.isAdmin()}">
                    <li id="home" class="header-section active">
                        <a href="/"><h:outputText value="#{msg['lang.home']}"/></a>
                    </li>
                    </c:if>
                    <c:if test="#{adminBean.isAdmin()}">
                        <li id="users" class="header-section"><a href="/users"><h:outputText
                                value="#{msg['lang.view']}"/></a></li>
                    </c:if>
                    <li id="about" class="header-section">
                        <a href="/about"><h:outputText value="#{msg['lang.about']}"/></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a>
                            <h:form>
                                <h:panelGrid columns="2">

                                    <h:outputText value="#{msg['lang.language']}"/>
                                    <h:selectOneMenu value="#{language.localeCode}" onchange="submit()"
                                                     valueChangeListener="#{language.countryLocaleCodeChanged}">
                                        <f:selectItems value="#{language.countriesInMap}"/>
                                    </h:selectOneMenu>

                                </h:panelGrid>

                            </h:form>
                        </a>
                    </li>
                    <c:if test="#{request.remoteUser.contains('@')}">
                        <li>
                            <form action="/appLogout" method="POST">
                                <input class="btn btn-logout" type="submit"
                                       value="#{msg['lang.logout']} #{request.remoteUser}"/>
                                <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
                            </form>
                        </li>
                    </c:if>
                    <c:if test="#{!request.remoteUser.contains('@')}">
                        <c:choose>
                            <c:when test="#{request.servletPath.equals('/signup.xhtml')}">
                                <li><a href="/"><span class="glyphicon glyphicon-user"/>
                                    #{msg['lang.login']}
                                </a></li>
                            </c:when>
                            <c:otherwise>
                                <li><a href="/reg"><span class="glyphicon glyphicon-user"/>
                                    #{msg['lang.register']}
                                </a></li>
                            </c:otherwise>
                        </c:choose>
                    </c:if>
                </ul>
            </div>
        </nav>
    </div>

</ui:composition>
<!--</body>-->
</html>

src/main/webapp/templates/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
>
<h:head>
    <title>#{msg['lang.page_name']}</title>
</h:head>
<body>
<ui:insert name="header">
    <ui:include src="header.xhtml"/>
</ui:insert>

<ui:insert name="content">
    <ui:include src="content.xhtml"/>
</ui:insert>

<ui:insert name="footer">
    <ui:include src="footer.xhtml"/>
</ui:insert>
</body>
</html>